apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: internal-app
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 3093
      targetPort: 3093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: internal-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 853647457900.dkr.ecr.ap-south-1.amazonaws.com/hackathonbackend:latest
        ports:
        - containerPort: 3093
